name: Tunio

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Release build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: -p tunio --release --all-features
    - name: Run tests
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: -p tunio --verbose
    - name: Check if can be packaged
      uses: actions-rs/cargo@v1
      with:
        command: package
        args: -p tunio

  publish:
    runs-on: ubuntu-latest
    needs: [build]
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - uses: actions/checkout@v3
      - name: Publish to Crates.io
        uses: actions-rs/cargo@v1
        with:
          command: publish
          args: -p tunio
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
